import { Inter } from "next/font/google";
import "./globals.css";

// Components
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// Theme provider
import { ThemeProvider } from "@/components/ThemeProvider";
import StartCanvas from "@/components/startBackground";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "OSC TOP SOLUTIONS GROUP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased overflow-y-scroll overflow-x-hidden`}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <Header />
          <StartCanvas />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
