import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Template from "@/app/Template"; // Ajusta la ruta según la ubicación real

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "OSC TOP SOLUTIONS GROUP",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased overflow-y-scroll overflow-x-hidden`}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <Template>
            {/* Renderiza el contenido principal */}
            {children}
          </Template>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
